### ISSUE TITLE
Dude, this doesnt work

### ISSUE THREAD

**Issue by balistikbill** [Centril/sublime-autohide-sidebar#1]
Doesn't work on my windows machine!

**Comment by Centril** [comment]
Please read the [README.md](https://github.com/Centril/sublime-autohide-sidebar/blob/master/README.md)

> This addon is in no way shape or form done - it is still in its development stages and is not for production use, use at your own risk.

**Comment by balistikbill** [comment]
Well, is it supposed to?  It seems to auto hide it one time when I open subliem and works nice.  I really wish Ic ould use this because I think it's a great feature.

**Comment by Centril** [comment]
No, it is not supposed to - new API features have been added to sublime text which I'll have to utilize to make it work properly. Also, I haven't done any development on this one for a long time.

**Comment by balistikbill** [comment]
Oh, you should, it would be a nice feature.

**Comment by balistikbill** [comment]
The other auto hide plugin doesn't work by the mouse it just works by when you type ten keys it hides the sidebar, I'd prefer the mouse.

**Comment by Centril** [comment]
I'm doing development on another project at the moment, so I don't have time to fix it... maybe later.
But you are free to fork and fix =)
